# Generated by Django 4.1.3 on 2022-12-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuctionListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slika', models.FileField(upload_to='')),
                ('naslov', models.CharField(max_length=24)),
                ('opis', models.CharField(max_length=240)),
                ('cena', models.IntegerField()),
                ('datum', models.DateTimeField()),
            ],
        ),
    ]
