# Generated by Django 4.1.3 on 2022-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='markovano',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='markovano',
            field=models.ManyToManyField(to='auctions.auctionlisting'),
        ),
    ]
