# Generated by Django 4.1.3 on 2022-12-03 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_remove_bookmarks_markovano_bookmarks_markovano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmarks',
            old_name='markovano',
            new_name='Bookmarks',
        ),
    ]
