# Generated by Django 4.1.3 on 2022-12-03 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_markovano_bookmarks_bookmarks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='Bookmarks',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='markovano',
            field=models.ManyToManyField(blank=True, related_name='povezati', to='auctions.auctionlisting'),
        ),
    ]
