# Generated by Django 4.1.3 on 2022-12-04 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_remove_bookmarks_bookmarks_bookmarks_markovano'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmarks',
            name='markovano',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='listing',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='povezano', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
