# Generated by Django 4.1.3 on 2022-12-04 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bookmarks_markovano_bookmarks_listing_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Komentar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('komentar', models.CharField(max_length=240)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kpovezano', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
