# Generated by Django 4.1.3 on 2022-12-04 14:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_komentar'),
    ]

    operations = [
        migrations.AddField(
            model_name='komentar',
            name='klisting',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='klistings', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
