# Generated by Django 4.1.3 on 2022-12-04 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auctionlisting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='kategorija',
            field=models.CharField(choices=[('TH', 'Tehnika'), ('KU', 'Kuca'), ('OD', 'Odeca')], default=1, max_length=15),
            preserve_default=False,
        ),
    ]
