# Generated by Django 4.1.3 on 2022-12-04 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_auctionlisting_kategorija'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='kategorija',
            field=models.CharField(choices=[('Tehnika', 'Tehnika'), ('Kuca', 'Kuca'), ('Odeca', 'Odeca')], max_length=15),
        ),
        migrations.CreateModel(
            name='Bids',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bids', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bpovezano', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
