# Generated by Django 4.1.3 on 2022-12-04 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0012_alter_auctionlisting_kategorija_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='krajb',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
