# Generated by Django 4.1.3 on 2022-12-04 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_alter_bids_options_auctionlisting_krajbiddinga'),
    ]

    operations = [
        migrations.AddField(
            model_name='bids',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bpovezano', to='auctions.auctionlisting'),
            preserve_default=False,
        ),
    ]
