# Generated by Django 4.1.4 on 2023-02-03 10:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_user_listing_alter_auctionlisting_slika_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='listing',
        ),
        migrations.CreateModel(
            name='Following',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfollower', to=settings.AUTH_USER_MODEL)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cfollowing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
