# Generated by Django 4.1.4 on 2023-02-03 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_remove_following_following_following_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nesto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
