# Generated by Django 4.1.4 on 2023-02-05 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0021_user_password1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='slika',
            field=models.ImageField(upload_to='images'),
        ),
    ]
